# Generated by Django 5.2 on 2025-04-23 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.BigIntegerField()),
                ('card_name', models.CharField(default='No Name', max_length=255)),
                ('card_type', models.CharField(default='No Type', max_length=255)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('card_effect', models.TextField(blank=True, null=True)),
                ('pend_effect', models.TextField(blank=True, null=True)),
                ('card_level', models.IntegerField(blank=True, null=True)),
                ('card_rank', models.IntegerField(blank=True, null=True)),
                ('link_rating', models.IntegerField(blank=True, null=True)),
                ('pend_scale', models.IntegerField(blank=True, null=True)),
                ('ban_status', models.IntegerField(blank=True, null=True)),
                ('image_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card_data',
                'unique_together': {('card_id', 'card_name')},
            },
        ),
        migrations.CreateModel(
            name='CardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.BigIntegerField()),
                ('card_name', models.CharField(default='No Name', max_length=255)),
                ('card_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='api.carddata')),
            ],
            options={
                'db_table': 'card_inventory',
                'unique_together': {('card_id', 'card_name')},
            },
        ),
    ]
